
mof_to_html_map = {'IBMUIMINV_SYSTEMOVERVIEW':'Computer System',
             'IBMUIMINV_MEMORY':'Memory',
             'IBMUIMINV_BIOS_AND_UEFI':'BIOS/uEFI',
             'IBMUIMINV_FIRMWARE':'Firmware',
             'IBMUIMINV_DEVICEDRIVERS':'Device Drivers',
             'IBMUIMINV_FODKEY':'Activation Key',
             'IBMUIMINV_LSICONTROLLERINFORMATION':'Controller Information',
             'IBMUIMINV_LSILOGICALDRIVES':'Logical drive information',
             'IBMUIMINV_LSIPHYSICALDRIVES':'Physical drive information',
             'IBMUIMINV_PMCAPPLICATIONSOFTWARE':''
			 'IBMUIMINV_PMCCARDCONTROLLER':
			 'IBMUIMINV_PMCLOGICALDISK':
			 'IBMUIMINV_PMCPHYSICALDISK':
			 'IBMUIMINV_MELLANOXDRIVER':'Driver',
			 'IBMUIMINV_MELLANOXFIRMARE':'Firmware Identity',
			 'IBMUIMINV_MELLANOXPCIDEVICE':'PCI Device',
			 'IBMUIMINV_MELLANOXETHERNETPORT':
			 'IBMUIMINV_MELLANOXIBPORT':'IB Port',
			 'IBMUIMINV_QLOGICFIBREFIRMWARES':'Qlogic Fibre Channel Firmware',
			 'IBMUIMINV_QLOGICFIBREBIOS':'Qlogic Fibre Channel BIOS',
			 'IBMUIMINV_QLOGICISCSIFIRMWARE':'Qlogic iSCSI Firmware',
             'IBMUIMINV_QLOGICISCSIBIOS':'Qlogic iSCSI BIOS',
			 'IBMUIMINV_BROCADEPORTCONTROLLER':'Port Controller',
			 'IBMUIMINV_BROCADEFCPORT':'FC Port',
			 'IBMUIMINV_BROCADEETHERNETPORT':'Ethernet Port',
			 'IBMUIMINV_BROCADESOFTWAREIDENTITY':'Adapter BIOS/FW Version',
			 'IBMUIMINV_BROCADCOMFIRMWARE':'Broadcom Firmware',
			 'IBMUIMINV_EMXCNAPRODUCT':'EMXCNA Product',
			 'IBMUIMINV_EMXCNAFIRMWARE':'EMXCNA Firmware',
			 'IBMUIMINV_EMXCNADRIVER':'EMXCNA Driver',
			 'IBMUIMINV_EMULEXFOD':'Emulex FoD Activation Information',
             'IBMUIMINV_IMMCONFIGIPV4_DHCP':'DHCP IPv4 Address',
			 'IBMUIMINV_IMMCONFIGIPV4_STATIC':'Static IPv4 Address',
			 'IBMUIMINV_IMMCONFIGIPV6_DHCP':'DHCP IPv6 Address',
             'IBMUIMINV_IMMCONFIGIPV6_STATELESS':'IPv6 Stateless Address',
             'IBMUIMINV_IMMCONFIGIPV6_LOCALLINK':'IPv6 Local Link Address',
             'IBMUIMINV_IMMCONFIGIPV6_STATIC':'Static IPv6 Address',

}
